### PR TITLE
Added Stuff like Hats, Trails, news feed, teams (partially working, you cant join a team), fully upgraded Dirtbike and Offroader, freindlist, leaderboard (partially works) and Chat (its broken).

### PR DESCRIPTION
**Pull request by Dodonickey**
i added more features to your server.

### CODE REVIEW

**Comment by EthanHervig** [comment]
Nice! Love the progress on the server so far 🔥On Nov 1, 2024, at 1:11 PM, Dodonickey ***@***.***> wrote:﻿i added more features to your server.



You can view, comment on, or merge this pull request online at:
  https://github.com/Jurij15/BigBangRacingRevival/pull/1

Commit Summary

  7fd8c44  Added Stuff like Hats, Trails, news feed, teams (partially working, you cant join a team), fully upgraded Dirtbike and Offroader, freindlist, leaderboard (partially works) and Chat (its broken).
  8cc5e2a  Revert "Added Stuff like Hats, Trails, news feed, teams (partially working, you cant join a team), fully upgraded Dirtbike and Offroader, freindlist, leaderboard (partially works) and Chat (its broken)."
  69dc3d1  Reapply "Added Stuff like Hats, Trails, news feed, teams (partially working, you cant join a team), fully upgraded Dirtbike and Offroader, freindlist, leaderboard (partially works) and Chat (its broken)."


File Changes  (5 files)

  
    M
    BBRRevival.ControlPanel/Services/ServerService.cs
    (2)
  
  
    M
    BBRRevival.Services/APIConfig.cs
    (2)
  
  
    M
    BBRRevival.Services/Controllers/LoginController.cs
    (471)
  
  
    M
    BBRRevival.Services/Controllers/SocialController.cs
    (39)
  
  
    A
    BBRRevival.Services/Controllers/TeamController.cs
    (74)
  


Patch Links:

  https://github.com/Jurij15/BigBangRacingRevival/pull/1.patch
  https://github.com/Jurij15/BigBangRacingRevival/pull/1.diff

**Comment by Dodonickey** [comment]
this was my first pull request so idk why the commit log is so long

**Comment by Jurij15** [comment]
I have created a new branch for this PR, and it will be merged there.

**Comment by Jurij15** [comment]
Merging to this branch.

**Comment by Dodonickey** [comment]
yipee 😁😁😁

**Pull request merged**
